name: Build and Publish Docs

on:
  push:
    branches:
      - main         # Adjust if your main branch is named differently
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Documentation Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies (so autodoc can import your modules)
          pip install -r requirements.txt
          # Install Sphinx and any required themes/extensions
          pip install Sphinx==7.4.7 \
                sphinx-autodoc-typehints==2.3.0 \
                sphinx-rtd-theme==3.0.2 \
                sphinxcontrib-applehelp==2.0.0 \
                sphinxcontrib-devhelp==2.0.0 \
                sphinxcontrib-htmlhelp==2.1.0 \
                sphinxcontrib-jquery==4.1 \
                sphinxcontrib-jsmath==1.0.1 \
                sphinxcontrib-qthelp==2.0.0 \
                sphinxcontrib-serializinghtml==2.0.0
                
      - name: Build Sphinx Documentation
        working-directory: docs
        run: |
          # This assumes you have a Makefile in your docs folder that builds HTML docs (e.g., via "make html")
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
